bulletin_board/server/config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
Rails.application.routes.draw do
  scope "/api" do
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api"
    get "/docs", to: "documentation#show", as: :documentation
    get "/", to: redirect("/api/docs")
    post "/", to: "graphql#execute", as: :api_endpoint
  end

  root to: "pages#index"

  if !Rails.env.production? || ENV.fetch("SANDBOX", nil)
    mount Sidekiq::Web => "/sidekiq"
    scope "/sandbox", module: :sandbox, as: :sandbox do
      resources :elections, only: [:new, :create, :index] do
        member do
          get :start_key_ceremony
          get :key_ceremony
          get :start_vote
          get :vote
          post :vote
          get :in_person_vote
          post :in_person_vote
          post :generate_bulk_votes
          get :download_bulk_votes
          get :load_test_stats
          get :end_vote
          get :start_tally
          get :tally
          post :report_missing_trustee
          get :publish_results
          get :results
        end
      end
    end
  end
end

bulletin_board/server/app/models/election.rb
# frozen_string_literal: true

class Election < ApplicationRecord
  belongs_to :authority
  has_many :election_trustees
  has_many :trustees, -> { order(id: :asc) }, through: :election_trustees
  has_many :log_entries, -> { order(id: :asc) }

  has_one_attached :verifiable_results

  enum status: { created: 0, key_ceremony: 1, key_ceremony_ended: 2, vote: 3, vote_ended: 4, tally_started: 5, tally_ended: 6, results_published: 7 }

  def manifest
    @manifest ||= log_entries.first.decoded_data
  end

  def voting_scheme_name
    @voting_scheme_name ||= manifest["scheme"]["name"]
  end

  def polling_stations
    @polling_stations ||= manifest["polling_stations"] || []
  end
end

bulletin_board/server/app/controllers/sandbox/elections_controller.rb
# frozen_string_literal: true

require "test/private_keys"
require "redis"

module Sandbox
  class ElectionsController < ApplicationController
    include RedisProvider

    helper_method :elections, :election,
                  :bulletin_board_server, :authority_slug, :authority_public_key,
                  :random_voter_id,
                  :election_results, :verifiable_results,
                  :default_bulk_votes_number, :bulk_votes_file_name, :bulk_votes_file_exists?, :generated_votes_number,
                  :bulk_votes_file_url, :bulk_votes_file_update_time, :bulk_votes_url_set?, :pending_message

    DEFAULT_BULK_VOTES_NUMBER = 1000

    def index; end

    def create
      bulletin_board_client.create_election(params[:election][:id], election_data)
      go_back
    end

    def start_key_ceremony
      bulletin_board_client.start_key_ceremony(election_id)
      go_back
    end

    def key_ceremony; end

    def start_vote
      bulletin_board_client.start_vote(election_id)
      go_back
    end

    def vote
      return unless request.post?

      pending_message = bulletin_board_client.cast_vote(election_id, params[:voter_id], params[:encrypted_ballot])

      render json: { data: pending_message.to_h }
    end

    def in_person_vote
      return unless request.post?

      @pending_message = bulletin_board_client.in_person_vote(election_id, params[:voter_id], params[:polling_station_id])
    end

    def generate_bulk_votes
      GenerateVotesJob.perform_later(number_of_votes_to_generate, election.id, bulk_votes_file_path(election), bulletin_board_settings_hash)
    end

    def download_bulk_votes
      return head(:not_foud) unless bulk_votes_file_exists?(election)

      send_file(
        bulk_votes_file_path(election),
        filename: bulk_votes_file_name(election),
        type: "text/csv"
      )
    end

    def load_test_stats
      Sandbox::GenerateLoadTestStats.new(election.id).call
      send_file(
        Sandbox::GenerateLoadTestStats::STATS_OUTPUT_FILE_PATH,
        type: "application/json"
      )
    end

    def end_vote
      bulletin_board_client.end_vote(election_id)
      go_back
    end

    def start_tally
      bulletin_board_client.start_tally(election_id)
      go_back
    end

    def tally; end

    def report_missing_trustee
      pending_message = bulletin_board_client.report_missing_trustee(election_id, params[:trustee_id])

      render json: { data: pending_message.to_h }
    end

    def publish_results
      bulletin_board_client.publish_results(election_id)
      go_back
    end

    def results
      results = bulletin_board_client.get_election_results(election_id)
      @election_results = results[:election_results]
      @verifiable_results = results[:verifiable_results]
    end

    private

    delegate :authority, to: :election
    delegate :bulletin_board_server, :authority_slug, to: :bulletin_board_client

    attr_reader :election_results, :verifiable_results, :pending_message

    def election_data
      @election_data ||= params.require(:election).permit(:default_locale, title: {}).to_h.merge(
        trustees:,
        start_date:,
        end_date:,
        polling_stations:,
        questions:,
        answers:,
        ballot_styles:
      )
    end

    def start_date
      @start_date ||= params[:election][:start_date].to_i.days.from_now
    end

    def end_date
      @end_date ||= start_date + params[:election][:end_date].to_i.days
    end

    def trustees
      @trustees ||= Trustee.first(3).map do |trustee|
        {
          name: trustee.name,
          slug: trustee.slug,
          public_key: trustee.public_key
        }
      end
    end

    def polling_stations
      @polling_stations ||= params[:election][:polling_stations].compact_blank
    end

    def questions
      @questions ||= params.require(:election).permit(questions: {})[:questions].to_h.values.map do |question|
        question.merge(
          max_selections: question[:max_selections].to_i,
          answers: question[:answers].values.map do |answer|
            {
              slug: answer[:slug]
            }
          end
        )
      end
    end

    def answers
      @answers ||= params.require(:election).permit(questions: {})[:questions].to_h.values.flat_map do |question|
        question[:answers].values.map do |answer|
          {
            slug: answer[:slug],
            title: answer[:title]
          }
        end
      end
    end

    def ballot_styles
      @ballot_styles ||= params.require(:election).permit(ballot_styles: {})[:ballot_styles].to_h.transform_values(&:keys)
    end

    def go_back
      redirect_to sandbox_elections_path
    end

    def authority
      Authority.first
    end

    def authority_public_key
      @authority_public_key ||= authority.public_key.to_json
    end

    def elections
      @elections ||= Election.order(:id)
    end

    def election
      @election ||= elections.find(params[:id])
    end

    def election_id
      @election_id ||= election.unique_id.split(".").last
    end

    def bulletin_board_client
      @bulletin_board_client ||= Decidim::BulletinBoard::Client.new(bulletin_board_settings)
    end

    def bulletin_board_settings
      @bulletin_board_settings ||= OpenStruct.new(bulletin_board_settings_hash)
    end

    def bulletin_board_settings_hash
      @bulletin_board_settings_hash ||= {
        bulletin_board_server: api_endpoint_url,
        bulletin_board_public_key: BulletinBoard.public_key,
        authority_api_key: authority.api_key,
        authority_name: authority.name,
        authority_private_key: Test::PrivateKeys.authority_private_key_json,
        scheme_name: params.dig(:election, :voting_scheme_name) || "dummy",
        quorum: 2,
        number_of_trustees: 3
      }
    end

    def random_voter_id
      @random_voter_id ||= SecureRandom.hex
    end

    def number_of_votes_to_generate
      params[:number_of_votes]&.to_i || 1000
    end

    def default_bulk_votes_number
      DEFAULT_BULK_VOTES_NUMBER
    end

    def bulk_votes_file_path(election)
      Rails.root.join("tmp", bulk_votes_file_name(election)).to_s
    end

    def bulk_votes_file_name(election)
      "bulk_votes_#{election.id}.csv"
    end

    def bulk_votes_file_exists?(election)
      File.exist?(bulk_votes_file_path(election))
    end

    def bulk_votes_url_set?(election)
      bulk_votes_file_url(election).present?
    end

    def bulk_votes_file_url(election)
      signed_id = redis.get("election-#{election.id}-votes-file:signed_id")
      blob = ActiveStorage::Blob.find_signed(signed_id) if signed_id

      url_for(blob) if blob
    end

    def bulk_votes_file_update_time(election)
      redis.get("election-#{election.id}-votes-file:time")
    end

    def generated_votes_number(election)
      `wc -l "#{bulk_votes_file_path(election)}"`.strip.split[0].to_i
    end
  end
end

bulletin_board/server/app/helpers/sandbox/elections_helper.rb
# frozen_string_literal: true

module Sandbox
  module ElectionsHelper
    def election_questions_with_answers(election)
      election.manifest.dig(:description, :contests).each_with_object({}) do |contest, acc|
        acc[contest[:object_id]] = contest[:ballot_selections].map { |ballot_selection| ballot_selection[:object_id] }
      end
    end

    def question_max_selections(question_id)
      election.manifest.dig(:description, :contests).find { |contest| contest["object_id"] == question_id }["number_elected"]
    end

    def has_ballot_styles?(election)
      election.manifest.dig(:description, :ballot_styles)&.any?
    end

    def options_for_ballot_style_select(election)
      options_for_select(election.manifest.dig(:description, :ballot_styles).map { |ballot_style| ballot_style["object_id"] })
    end

    def ballot_style_classes(question_id)
      (election.manifest.dig(:description, :ballot_styles) || []).map do |ballot_style|
        if ballot_style["contests"].include?(question_id)
          ballot_style["object_id"]
        else
          ""
        end
      end.join(" ")
    end

    def has_polling_stations?(election)
      election.manifest[:polling_stations]&.any?
    end

    def options_for_polling_station_select(election)
      options_for_select(election.manifest[:polling_stations])
    end
  end
end

bulletin_board/server/app/views/sandbox/elections/in_person_vote.html.erb
<%= stylesheet_link_tag "sandbox/in_person_vote" %>

<section class="in_person_vote">
  <div class="in_person_vote__intro">
    <div class="version">Bulletin Board Version <%= Decidim::BulletinBoard::VERSION %></div>

    <h1>In person vote for <%= election.title.values.first %></h1>
    <%= link_to "Back", sandbox_elections_path, class: "button" %>
  </div>

  <% if pending_message %>
    <div class="in_person_vote__pending_message">
      Previous request status:
      <span
        class="js-pending-message"
        data-api-endpoint-url="<%= bulletin_board_server %>"
        data-message-id="<%= pending_message.message_id %>">
        enqueued
      </span>.
    </div>
  <% end %>

  <form class="in_person_vote__form voter" method="post" action="<%= in_person_vote_sandbox_election_path(election) %>">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <div class="in_person_vote__form-row">
      <div class="in_person_vote__form-column">
        <div class="in_person_vote__form-field">
          <label for="voter_id">Voter ID</label>
          <input id="voter_id" name="voter_id" value="<%= random_voter_id %>">
        </div>
      </div>
      <div class="in_person_vote__form-column">
        <div class="in_person_vote__form-field">
          <label for="polling_station_id">Polling station</label>
          <select id="polling_station_id" name="polling_station_id">
            <%= options_for_polling_station_select(election) %>
          </select>
        </div>
      </div>
    </div>
    <div class="in_person_vote__form-actions">
      <button>In person vote</button>
    </div>
  </form>
</section>

<%= javascript_include_tag "sandbox/in_person_vote" %>

bulletin_board/server/app/views/sandbox/elections/index.html.erb
<%= stylesheet_link_tag "sandbox/index" %>

<section class="index">
  <div class="index__intro">
    <div class="version">Bulletin Board Version <%= Decidim::BulletinBoard::VERSION %></div>

    <h1>Elections</h1>
    <%= link_to "Back", root_path, class: "button" %>
    <%= link_to "Setup new election", new_sandbox_election_path, class: "button" %>
  </div>

  <div class="index__content">
    <table>
      <thead>
        <tr>
          <th>Unique ID</th>
          <th>Title</th>
          <th>Status</th>
          <th>Voting Scheme</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% elections.each do |election| %>
          <tr class="election" data-id="<%= election.id %>">
            <td><%= election.unique_id %></td>
            <td><%= election.title.values.first %></td>
            <td><%= election.status %></td>
            <td><%= election.voting_scheme_name %></td>
            <td>
              <% if election.created? %>
                <%= link_to "Start key ceremony", start_key_ceremony_sandbox_election_path(election), class: "button" %>
              <% elsif election.key_ceremony? %>
                <%= link_to "Perform key ceremony", key_ceremony_sandbox_election_path(election), class: "button" %>
              <% elsif election.key_ceremony_ended? %>
                <%= link_to "Start vote", start_vote_sandbox_election_path(election), class: "button" %>
              <% elsif election.vote? %>
                <%= link_to "Vote", vote_sandbox_election_path(election), class: "button" %>
                <% if has_polling_stations?(election) %>
                  <%= link_to "In Person Vote", in_person_vote_sandbox_election_path(election), class: "button" %>
                <% end %>
                <%= link_to "End vote", end_vote_sandbox_election_path(election), class: "button" %>
                <a href="#" class="stress-tests button <%= "pressed" if bulk_votes_file_exists?(election) %>">Stress tests</a>
                <div class="stress-tests-section">
                  <input class="generate-votes-input" type="number" placeholder="How many votes?" value="<%= default_bulk_votes_number %>"/>
                  <a href="#" class="generate-votes button">Generate votes</a>
                  <%= link_to "Load test stats", load_test_stats_sandbox_election_path(election), download: Sandbox::GenerateLoadTestStats::STATS_OUTPUT_FILE_NAME, class: "button" %>
                  <% if bulk_votes_url_set?(election) %>
                    <%= link_to "Download votes", bulk_votes_file_url(election), download: bulk_votes_file_name(election), class: "button", target: "_blank" %>
                    <p><%= "Bulk votes file last updated at: #{bulk_votes_file_update_time(election)}"%></p>
                  <% end %>
                </div>
              <% elsif election.vote_ended? %>
                <%= link_to "Start tally", start_tally_sandbox_election_path(election), class: "button" %>
              <% elsif election.tally_started? %>
                <%= link_to "Perform tally", tally_sandbox_election_path(election), class: "button" %>
              <% else %>
                <%= link_to "View results", results_sandbox_election_path(election), class: "button" %>
                <%= link_to "Publish results", publish_results_sandbox_election_path(election), class: "button" if election.tally_ended? %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

<%= javascript_include_tag "sandbox/index" %>

bulletin_board/server/app/views/sandbox/elections/key_ceremony.html.erb
<%= stylesheet_link_tag "sandbox/key_ceremony" %>

<section class="key_ceremony">
  <div class="key_ceremony__intro">
    <div class="version">Bulletin Board Version <%= Decidim::BulletinBoard::VERSION %></div>

    <h1>Key ceremony for <%= election.title.values.first %></h1>
    <%= link_to "Back", sandbox_elections_path, class: "button" %>
  </div>

  <div class="key_ceremony__content">
    <h2>Trustees</h2>

    <p>You can find the trustee keys in the project's <code>lib/assets</code> folder.</p>

    <table class="trustee-table"
          data-election-unique-id="<%= election.unique_id %>"
          data-api-endpoint-url="<%= bulletin_board_server %>"
          data-authority-public-key="<%= authority_public_key %>"
          data-voting-scheme-name="<%= election.voting_scheme_name %>">
      <thead>
        <tr>
          <th>Unique ID</th>
          <th>Slug</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% election.trustees.each do |trustee| %>
          <tr data-unique-id="<%= trustee.slug %>" data-public-key="<%= trustee.public_key.to_json %>">
            <td><%= trustee.unique_id %></td>
            <td><%= trustee.slug %></td>
            <td><%= trustee.name %></td>
            <td>
              <label class="upload-private-key-button">
                <span>Upload private key</span>
                <input class="private-key-input" style="display: none" type="file" />
              </label>
              <%= link_to "Start", "#", class: "start-button button" %>
              <%= link_to "Backup", "#", class: "backup-button button" %>
              <label class="restore-button">
                <span>Restore</span>
                <input class="restore-button-input" style="display: none" type="file" />
              </label>
              <span class="done-message">Done</span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

<%= javascript_include_tag "sandbox/key_ceremony" %>

bulletin_board/server/app/views/sandbox/elections/new.html.erb
<%= stylesheet_link_tag "sandbox/new" %>

<section class="new_election">
  <div class="new_election__intro">
    <div class="version">Bulletin Board Version <%= Decidim::BulletinBoard::VERSION %></div>

    <h1>Create election</h1>
    <%= link_to "Back", sandbox_elections_path, class: "button" %>
  </div>

  <form class="new_election__form" method="post" action="<%= sandbox_elections_path %>">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <div class="new_election__form-row">
      <div class="new_election__form-column">
        <div class="new_election__form-field">
          <label for="election_voting_scheme_name">Voting scheme name</label>
          <select id="election_voting_scheme_name" name="election[voting_scheme_name]">
            <option value="dummy">dummy</option>
            <option value="electionguard">electionguard</option>
          </select>
        </div>
        <div class="new_election__form-field">
          <label for="election_id">Election ID</label>
          <input id="election_id" name="election[id]" type="text" value="<%= SecureRandom.base58 %>">
        </div>
        <div class="new_election__form-field">
          <label for="election_default_locale">Default locale</label>
          <select id="election_default_locale" name="election[default_locale]">
            <option>ca</option>
            <option selected>en</option>
            <option>es</option>
          </select>
        </div>
        <div class="new_election__form-field">
          <label for="election_title">Election title</label>
          <input id="election_title" name="election[title][ca]" type="text" value="Votació de prova" placeholder="ca">
          <input name="election[title][en]" type="text" value="Test election" placeholder="en">
          <input name="election[title][es]" type="text" value="Votación de prueba" placeholder="es">
        </div>
      </div>
      <div class="new_election__form-column">
        <div class="new_election__form-field">
          <label for="election_start_date">Start date</label>
          <input id="election_start_date" name="election[start_date]" type="number" value="1"> days from now
        </div>
        <div class="new_election__form-field">
          <label for="election_end_date">End date</label>
          <input id="election_end_date" name="election[end_date]" type="number" value="1"> after the start
        </div>
        <div class="new_election__form-field">
          <label for="election_polling_stations">Polling stations</label>
          <input id="election_polling_stations" name="election[polling_stations][]" value="polling-station-1">
          <input name="election[polling_stations][]" value="polling-station-2">
          <input name="election[polling_stations][]" value="polling-station-3">
          <input name="election[polling_stations][]" value="">
          <input name="election[polling_stations][]" value="">
          <input name="election[polling_stations][]" value="">
          <input name="election[polling_stations][]" value="">
          <input name="election[polling_stations][]" value="">
        </div>
      </div>
    </div>
    <h2>Questions</h2>
    <div class="new_election__form-questions-placeholder"></div>
    <button class="new_election__add-question-button">Add question</button>
    <h2>Ballot styles</h2>
    <div class="new_election__form-ballot-styles-placeholder"></div>
    <button class="new_election__add-ballot-style-button">Add ballot style</button>
    <div class="new_election__form-actions">
      <input type="submit" value="Create">
    </div>
  </form>
</section>

<template class="question-template">
  <h3>Question {{questionIndexPlusOne}}</h3>
  <div class="new_election__form-row election-question">
    <div class="new_election__form-column">
      <div class="new_election__form-field">
        <label for="election_questions_{{questionIndex}}_title">Title</label>
        <input id="election_questions_{{questionIndex}}_title" name="election[questions][{{questionIndex}}][title][ca]" type="text" value="Pregunta {{questionIndexPlusOne}}" placeholder="ca">
        <input name="election[questions][{{questionIndex}}][title][en]" type="text" value="Question {{questionIndexPlusOne}}" placeholder="en">
        <input name="election[questions][{{questionIndex}}][title][es]" type="text" value="Pregunta {{questionIndexPlusOne}}" placeholder="es">
      </div>
      <div class="new_election__form-field">
        <label for="election_questions_{{questionIndex}}_description">Description</label>
        <input id="election_questions_{{questionIndex}}_description" name="election[questions][{{questionIndex}}][description][ca]" type="text" value="Descripció {{questionIndexPlusOne}}" placeholder="ca">
        <input name="election[questions][{{questionIndex}}][description][en]" type="text" value="Description {{questionIndexPlusOne}}" placeholder="en">
        <input name="election[questions][{{questionIndex}}][description][es]" type="text" value="Descripción {{questionIndexPlusOne}}" placeholder="es">
      </div>
    </div>
    <div class="new_election__form-column">
      <div class="new_election__form-field">
        <label for="election_questions_{{questionIndex}}_slug">Slug</label>
        <input id="election_questions_{{questionIndex}}_slug" name="election[questions][{{questionIndex}}][slug]" type="text" value="question-{{questionIndexPlusOne}}">
      </div>
      <div class="new_election__form-field">
        <label for="election_questions_{{questionIndex}}_max_selections">Maximum selections</label>
        <input id="election_questions_{{questionIndex}}_max_selections" name="election[questions][{{questionIndex}}][max_selections]" type="number" value="{{questionIndexPlusOne}}" min="1" max="4">
      </div>
    </div>
  </div>
  <h4>Answers</h4>
  <% 3.times do |i| %>
    <div class="new_election__form-row">
      <div class="new_election__form-column">
        <div class="new_election__form-field">
          <label for="election_questions_{{questionIndex}}_answers_<%= i %>_title">Title</label>
          <input id="election_questions_{{questionIndex}}_answers_<%= i %>_title" name="election[questions][{{questionIndex}}][answers][<%= i %>][title][ca]" type="text" value="Resposta {{questionIndexPlusOne}}.<%= i+1 %>" placeholder="ca">
          <input name="election[questions][{{questionIndex}}][answers][<%= i %>][title][en]" type="text" value="Answer {{questionIndexPlusOne}}.<%= i+1 %>" placeholder="en">
          <input name="election[questions][{{questionIndex}}][answers][<%= i %>][title][es]" type="text" value="Respuesta {{questionIndexPlusOne}}.<%= i+1 %>" placeholder="es">
        </div>
      </div>
      <div class="new_election__form-column">
        <div class="new_election__form-field">
          <label for="election_questions_{{questionIndex}}_answers_<%= i %>_slug">Slug</label>
          <input id="election_questions_{{questionIndex}}_answers_<%= i %>_slug" name="election[questions][{{questionIndex}}][answers][<%= i %>][slug]" type="text" value="question-{{questionIndexPlusOne}}-<%= i+1 %>">
        </div>
      </div>
    </div>
  <% end %>
</template>

<template class="ballot-style-template">
  <h3>Ballot Style {{ballotStyleIndexPlusOne}}</h3>
  <div class="new_election__form-row ballot-style new_election__form-ballot-style-questions-placeholder"></div>
</template>

<template class="ballot-style-question-template">
  <div class="new_election__form-column">
    <label>
      <input type="checkbox" name="election[ballot_styles][ballot-style-{{ballotStyleIndexPlusOne}}][question-{{questionIndexPlusOne}}]" checked>
      question-{{questionIndexPlusOne}}
    </label>
  </div>
</template>

<%= javascript_include_tag "sandbox/new" %>

bulletin_board/server/app/views/sandbox/elections/results.html.erb
<%= stylesheet_link_tag "sandbox/results" %>

<section class="results">
  <div class="results__intro">
    <div class="version">Bulletin Board Version <%= Decidim::BulletinBoard::VERSION %></div>

    <h1>Results for <%= election.title.values.first %></h1>
    <%= link_to "Back", sandbox_elections_path, class: "button" %>
  </div>

  <div class="results__content">
    <h2>Results</h2>
    <% election_results.each do |question, answers| %>
      <h4><%= question %></h4>
      <ul>
        <% answers.each do |answer, votes| %>
          <li><%= answer %>: <%= votes %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="results__content">
    <h2>Verifiable Results</h2>
      <ul>
        <li><strong>Hash</strong>: <%= verifiable_results[:hash] %></li>
        <li><strong>File</strong>: <%= link_to "download here", verifiable_results[:url] %></li>
      </ul>
  </div>
</section>

bulletin_board/server/app/views/sandbox/elections/tally.html.erb
<%= stylesheet_link_tag "sandbox/tally" %>

<section class="tally">
  <div class="tally__intro">
    <div class="version">Bulletin Board Version <%= Decidim::BulletinBoard::VERSION %></div>

    <h1>Tally for <%= election.title.values.first %></h1>
    <%= link_to "Back", sandbox_elections_path, class: "button" %>
  </div>

  <div class="tally__content">
    <h2>Trustees</h2>

    <p>You can find the trustee keys in the project's <code>lib/assets</code> folder.</p>

    <table class="trustee-table"
          data-election-unique-id="<%= election.unique_id %>"
          data-api-endpoint-url="<%= bulletin_board_server %>"
          data-authority-public-key="<%= authority_public_key %>"
          data-voting-scheme-name="<%= election.voting_scheme_name %>">
      <thead>
        <tr>
          <th>Unique ID</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% election.trustees.each do |trustee| %>
          <tr data-unique-id="<%= trustee.slug %>" data-public-key="<%= trustee.public_key.to_json %>">
            <td><%= trustee.unique_id %></td>
            <td><%= trustee.name %></td>
            <td>
              <%= link_to "Start", "#", class: "start-button button" %>
              <%= link_to "Report as missing", "#", class: "report-missing button", data: { url: report_missing_trustee_sandbox_election_path(election, trustee_id: trustee.slug) } %>
              <%= link_to "Generate backup", "#", class: "generate-backup-button button" %>
              <label class="restore-button button">
                <span>Restore</span>
                <input class="restore-button-input button" style="display: none" type="file" />
              </label>
              <span class="done-message">Done</span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

<%= javascript_include_tag "sandbox/tally" %>

bulletin_board/server/app/views/sandbox/elections/vote.html.erb
<%= stylesheet_link_tag "sandbox/vote" %>

<section class="vote">
  <div class="vote__intro">
    <div class="version">Bulletin Board Version <%= Decidim::BulletinBoard::VERSION %></div>

    <h1>Vote for <%= election.title.values.first %></h1>
    <%= link_to "Back", sandbox_elections_path, class: "button" %>
    <a href="" class="button">Refresh</a>
  </div>

  <form
    class="vote__form voter"
    data-election-unique-id="<%= election.unique_id %>"
    data-api-endpoint-url="<%= bulletin_board_server %>"
    data-authority-public-key="<%= authority_public_key %>"
    data-voting-scheme-name="<%= election.voting_scheme_name %>">
    <div class="vote__form-row">
      <div class="vote__form-column">
        <div class="vote__form-field">
          <label for="voter_id">Voter ID</label>
          <input id="voter_id" name="voter_id" value="<%= random_voter_id %>">
        </div>
      </div>
      <% if has_ballot_styles?(election) %>
        <div class="vote__form-column">
          <div class="vote__form-field">
            <label for="ballot_style">Ballot Style</label>
            <select id="ballot_style" name="ballot_style">
              <%= options_for_ballot_style_select(election) %>
            </select>
          </div>
        </div>
      <% end %>
    </div>
    <div class="vote__form-row">
      <% election_questions_with_answers(election).each do |question_id, answer_ids| %>
        <div class="vote__form-column question <%= ballot_style_classes(question_id) %>">
          <p><%= question_id %> (limit = <%= question_max_selections(question_id) %>)</p>
          <% answer_ids.each do |answer_id| %>
            <label>
              <input name="<%= question_id %>" value="<%= answer_id %>" type="checkbox" <%= Random.rand > 0.5 ? 'checked' : '' %> class="answer" data-limit="<%= question_max_selections(question_id) %>">
              <%= answer_id %>
            </label>
          <% end %>
          <input name="<%= question_id %>" type="hidden">
        </div>
      <% end %>
    </div>
    <p class="benchmark"></p>
    <p class="ballot-hash"></p>
    <p class="done-message">
      Your vote has been sent to the server. It's status is
        <span class="pending-message">enqueued</span>.
    </p>
    <p class="audit-done-message">Your vote has been audited successfully</p>
    <div class="vote__form-actions">
      <button type="button" class="encrypt-vote">Encrypt vote</button>
      <button type="button" class="audit-vote">Audit vote</button>
      <button type="button" class="cast-vote">Cast vote</button>
    </div>
  </form>
</section>

<%= javascript_include_tag "sandbox/vote" %>