bulletin_board/server/config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
Rails.application.routes.draw do
  scope "/api" do
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api"
    get "/docs", to: "documentation#show", as: :documentation
    get "/", to: redirect("/api/docs")
    post "/", to: "graphql#execute", as: :api_endpoint
  end

  root to: "pages#index"

  if !Rails.env.production? || ENV.fetch("SANDBOX", nil)
    mount Sidekiq::Web => "/sidekiq"
    scope "/sandbox", module: :sandbox, as: :sandbox do
      resources :elections, only: [:new, :create, :index] do
        member do
          get :start_key_ceremony
          get :key_ceremony
          get :start_vote
          get :vote
          post :vote
          get :in_person_vote
          post :in_person_vote
          post :generate_bulk_votes
          get :download_bulk_votes
          get :load_test_stats
          get :end_vote
          get :start_tally
          get :tally
          post :report_missing_trustee
          get :publish_results
          get :results
        end
      end
    end
  end
end

bulletin_board/server/app/views/pages/index.html.erb
<div class="intro">
  <div class="version">Bulletin Board Version <%= Decidim::BulletinBoard::VERSION %></div>
  <h1>Welcome to this Decidim Bulletin Board instance!</h1>

  <p>The public key used by this instance to sign all the messages is the following:</p>
  <pre>
<%= JSON.pretty_generate(public_key) %>
  </pre>
</div>

<div class="info">
  <p>More information on the following links:</p>
  <ul>
  <li><a href="<%= documentation_path %>">API documentation</a></li>
  <li><a href="<%= graphiql_rails_path %>">GraphiQL user interface</a></li>
  <% if try(:sandbox_elections_path) %>
    <li><a href="<%= sandbox_elections_path %>">Elections sandbox</a></li>
  <% end %>
  </ul>
</div>